import streamlit as st
import requests
import pandas as pd
import pandas_ta as ta
import plotly.express as px
from google import genai

# Page Config
st.set_page_config(page_title="AI Forex Assistant Pro", page_icon="📈", layout="wide")

# Fetch credentials securely from secrets
FMP_API_KEY = st.secrets["FMP_API_KEY"]
try:
    GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    ai_client = genai.Client(api_key=GEMINI_API_KEY)
except Exception:
    ai_client = None

# --- Data Fetching Functions ---
@st.cache_data(ttl=60)
def fetch_forex_rates():
    url = f"https://financialmodelingprep.com{FMP_API_KEY}"
    try:
        response = requests.get(url)
        return response.json() if response.status_code == 200 else []
    except:
        return []

@st.cache_data(ttl=300)
def fetch_historical_forex(pair):
    url = f"https://financialmodelingprep.com{pair}?apikey={FMP_API_KEY}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            return data.get("historical", [])
    except:
        pass
    return []

# --- Title Block ---
st.title("💱 AI Forex Assistant Pro")
st.caption("Real-Time Analytics, Technical Indicators, and Generative AI Commentary")

# --- Sidebar Configuration ---
st.sidebar.header("🎯 System Control Panel")
major_pairs = ["EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD"]
selected_pair = st.sidebar.selectbox("Select Currency Pair", major_pairs)

# --- Feature 1: Real-Time Alert System ---
st.sidebar.markdown("---")
st.sidebar.subheader("🚨 Live Rate Alerts")
alert_target = st.sidebar.number_input(f"Alert if {selected_pair} drops below:", value=1.0000, format="%.4f")
enable_alerts = st.sidebar.checkbox("Activate Alert Watcher")

raw_rates = fetch_forex_rates()
current_live_price = None

if raw_rates:
    for rate in raw_rates:
        if rate.get('ticker') == selected_pair:
            current_live_price = float(rate.get('bid', 0.0))
            break

if enable_alerts and current_live_price:
    if current_live_price < alert_target:
        st.error(f"🚨 ALERT TRIGGERED: {selected_pair} has dropped to {current_live_price:.4f}! (Target: {alert_target:.4f})")
    else:
        st.sidebar.success(f"✅ Live Price ({current_live_price:.4f}) is above target.")

# --- Process Historical Data & Calculate Indicators ---
hist_data = fetch_historical_forex(selected_pair)

if hist_data:
    df = pd.DataFrame(hist_data)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(by='date', ascending=True)
    
    # --- Feature 2: Technical Indicators (RSI & MACD) ---
    df.ta.rsi(close='close', length=14, append=True)
    df.ta.macd(close='close', fast=12, slow=26, signal=9, append=True)
    
    # Clean up column names generated by pandas_ta
    df.columns = [col.replace('RSI_14', 'RSI').replace('MACD_12_26_9', 'MACD').replace('MACDs_12_26_9', 'MACD_Signal') for col in df.columns]

    # Quick Metrics Layout
    latest_row = df.iloc[-1]
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Current Price", f"{latest_row['close']:.4f}")
    m2.metric("RSI (14)", f"{latest_row['RSI']:.2f}" if 'RSI' in df.columns else "N/A")
    m3.metric("MACD Line", f"{latest_row['MACD']:.5f}" if 'MACD' in df.columns else "N/A")
    m4.metric("MACD Signal", f"{latest_row['MACD_Signal']:.5f}" if 'MACD_Signal' in df.columns else "N/A")

    # Layout for Charts
    tab1, tab2 = st.tabs(["📊 Price & Trend", "📈 Technical Indicators"])
    
    with tab1:
        fig_price = px.line(df, x='date', y='close', title=f"{selected_pair} Closing Price Trend", template="plotly_dark")
        st.plotly_chart(fig_price, use_container_width=True)
        
    with tab2:
        col_rsi, col_macd = st.columns(2)
        with col_rsi:
            if 'RSI' in df.columns:
                fig_rsi = px.line(df, x='date', y='RSI', title="Relative Strength Index (RSI)", template="plotly_dark")
                fig_rsi.add_hline(y=70, line_dash="dash", line_color="red", annotation_text="Overbought")
                fig_rsi.add_hline(y=30, line_dash="dash", line_color="green", annotation_text="Oversold")
                st.plotly_chart(fig_rsi, use_container_width=True)
        with col_macd:
            if 'MACD' in df.columns:
                fig_macd = px.line(df, x='date', y=['MACD', 'MACD_Signal'], title="MACD Convergence/Divergence", template="plotly_dark")
                st.plotly_chart(fig_macd, use_container_width=True)

    # --- Feature 3: LLM Market Advisor ---
    st.markdown("---")
    st.subheader("🤖 AI Market Advisor Commentary")
    
    if ai_client:
        if st.button("Generate AI Market Breakdown"):
            with st.spinner("Analyzing market structure and technicals..."):
                # Compile a brief text summary of current data for the LLM context
                market_summary = f"""
                Currency Pair: {selected_pair}
                Current Price: {latest_row['close']}
                30-Day High: {df['high'].max()}
                30-Day Low: {df['low'].min()}
                Current RSI (14): {latest_row.get('RSI', 'N/A')}
                Current MACD: {latest_row.get('MACD', 'N/A')}
                Current MACD Signal: {latest_row.get('MACD_Signal', 'N/A')}
                """
                
                prompt = f"""
                You are a senior hedge fund FX strategist. Analyze the following technical data and provide a concise, sharp market summary. 
                Identify potential support/resistance implications from the RSI and MACD setup, and outline a risk-managed trade idea. Keep it professional and straightforward.
                
                Data:
                {market_summary}
                """
                
                try:
                    response = ai_client.models.generate_content(
                        model='gemini-2.5-flash',
                        contents=prompt,
                    )
                    st.info(response.text)
                except Exception as e:
                    st.error(f"Failed to generate AI analysis: {e}")
    else:
        st.warning("To unlock AI commentary, add your `GEMINI_API_KEY` to the `.streamlit/secrets.toml` file.")
else:
    st.info("No data available to parse indicators.")
